### PR TITLE
Apr change

### LINKED ISSUE #482: Earn table APR - update to 7days data
currently, we use 24h data to calculate the APR we show.
we would like to change this and use a 7days value instead.

### PR DESCRIPTION
**Pull request by RanCohenn**
Fixed #482

### CODE REVIEW

**Review by zavelevsky — APPROVED** [review]
LGTM

**Review by zavelevsky — APPROVED** [review]
LGTM

**Review by ashachaf — COMMENTED** [review]
- [ ] make sure you include autocompounding rewards in the total you calculate (even if the value is 0 for now)
const totalApr7d = toBigNumber(tradingFeesApr7d)
    .plus(standardRewardsApr7d)
    .toNumber();
- [x] calcApr is always using 365 which is only correct for 14h data
export const calcApr = (
  fees: BigNumber | string | number,
  liquidity: BigNumber | string | number
): number =>
  Number(liquidity) === 0
    ? 0
    : toBigNumber(fees).times(365).div(liquidity).times(100).toNumber();

**Review by zavelevsky — DISMISSED** [review]
LGTM

**Comment by ashachaf** [comment]
- [ ] earn v2 APR numbers are off
production url:
image

preview link:
image

**Review by ashachaf — APPROVED** [review]

**Pull request merged**
