### PR TITLE
Feature: #585 - 0x Support

### PR DESCRIPTION
**Pull request by pingustar**
#585

### CODE REVIEW

**Comment by ashachaf** [comment]
- [ ] trying to get external rate shows blank page
flow:
1. open trade (wallet not connected)
2. try to swap eth->friesDAO
3. input 0.01 eth
expected: see the return amount
actual: 
image


- [ ] error handling - INSUFFICIENT_ASSET_LIQUIDITY 
flow:
1. try to trade eth->hmr (https://d6649bbc.falafel.pages.dev/trade?from=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&to=0xB1A30851E3f7d841b231B086479608e17198363A)
2. get api response
```{"code":100,"reason":"Validation Failed","validationErrors":[{"field":"sellAmount","code":1004,"reason":"INSUFFICIENT_ASSET_LIQUIDITY"}]}```
https://api.0x.org/swap/v1/price?sellToken=0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE&buyToken=0xB1A30851E3f7d841b231B086479608e17198363A&sellAmount=10000000000000000000
expected: use the error message to indicate to the user.
If error = INSUFFICIENT_ASSET_LIQUIDITY -> disable the CTA and indicate in the CTA text "Insufficient pool liquidity"

- [ ] incorrect - show rate when there is no liquidity
flow:
1. open trade
2. try to trade 0.01 eth->fkx (should return 0 and api return error indicated above)
3. try to trade 0.01 eth->bnt
4. try to trade 0.01 eth->fkx
expected: show 0 
actual: show some rate (which is not correct for the token)

**Comment by pingustar** [comment]
- [ ] update gtm event

**Comment by ashachaf** [comment]
- [ ] add affiliate to price quote
flow:
1. open trade widget
2. input 0.01 eth -> spwn
expected: return spwn amount will include/deduct the affiliate fee
actual: the returned value doesnt include the affiliate fee which might result in seeing a higher amount than expected

- [ ] incorrect price impact indication
flow:
1. open trade widget
2. input 23000 spwn -> eth
expected: api returns "price impact = 0", so we should show the same value.
actual: we show price impact = 100% on the frontend.
image

- [ ] wallet switching possible issue

- [ ] token USD value
image

**Review by zavelevsky — APPROVED** [review]
LGTM

**Comment by ashachaf** [comment]
- [ ] 
image

- [ ] 
image

**Review by ashachaf — APPROVED** [review]

**Pull request merged**
